### ISSUE TITLE
What parameters should be adjusted?

### ISSUE THREAD

**Issue by 1327476339** [zju3dv/PGSR#11]
by default parameters, but result is not ideal.
--max_abs_split_points 0 --opacity_cull_threshold 0.05
![image](https://github.com/user-attachments/assets/101ca0f1-ab13-4dd4-97be-8b0d814aad84)
![image](https://github.com/user-attachments/assets/866edcd1-53c5-451f-8839-1b8650184fd2)

**Comment by danpeng2** [comment]
Could you please send an RGB image? This will help us understand the texture of the floor and background.

**Comment by ywcmaike** [comment]
<img width="705" alt="image" src="https://github.com/user-attachments/assets/e66ec5c4-cf7c-409c-9bd7-473897c03a7e">
I have tried to reconstruct the static human face with pgsr‘s default setting, and it works well. If you want to construct the pure human, you may need to use the segmentation mask.

If the scene is dynamic, pgsr won't work well enough. We have developed a new method to reconstruct the surface of dynamic scenes and we are writing the paper. We may release the paper and the code early next month.

![image](https://github.com/user-attachments/assets/35c98e17-51c2-4927-ba62-0c38616987c5)

**Comment by LaFeuilleMorte** [comment]
> <img alt="image" width="705" src="https://private-user-images.githubusercontent.com/14950822/351186111-e66ec5c4-cf7c-409c-9bd7-473897c03a7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDE5NTcsIm5iZiI6MTcyMzMwMTY1NywicGF0aCI6Ii8xNDk1MDgyMi8zNTExODYxMTEtZTY2ZWM1YzQtY2Y3Yy00MDljLTliZDctNDczODk3YzAzYTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE0NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhN2YyNzEyNjg3YWE3NTFlOGU1ZGVkNWUzZWEwNTRiZTg3NGY4ODI2ZTg2Y2YyOGJlMTlmYzQ4YjI3OGVkYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MdYHPmfCa3SqDMb2vkktBXG3fkxkSz5GZAjqfM5bOGw">
> I have tried reconstructing the static human face with PGSR‘s default setting, which works well. If you want to construct the pure human, you may need to use the segmentation mask.
> 
> If the scene is dynamic, PGSR won't work well enough. We have developed a new method to reconstruct the surface of dynamic scenes and the paper is writing now. We may release the paper and the code early next month.
> 
>  hellwarrior.mp4

That's so cool
