### ISSUE TITLE
Memory consumption during evaluation

### ISSUE THREAD

**Issue by Harryqu123** [zju3dv/PGSR#12]
Dear authors,

Thanks for your great work! 

I am opening this issue since during my running of the code on my RTX 3090, I face an extremely high memory consumption during running the following [line of code during evaluation](https://github.com/zju3dv/PGSR/blob/main/scripts/run_dtu.py#L24)(https://github.com/zju3dv/PGSR/blob/main/scripts/run_dtu.py#L24), and thus fail to perform the evaluation.

After my quick localizing of the place that leads to this high memory consumption, I find that it happens [here](https://github.com/zju3dv/PGSR/blob/main/scripts/dtu_eval.py#L123):

rnn_idxs = nn_engine.radius_neighbors(data_pcd, radius=thresh, return_distance=False)

Could I please kindly know if you have any idea on the reason behond this?

Or possibly, could you please share the sklearn version that you use in your environment?

Looking forward to your reply and many thanks in advance.

**Comment by danpeng2** [comment]
Hello, thank you for your interest in our work. This script runs purely on the CPU and does not use GPU computation. Do you mean that the system memory is insufficient? Our Sklearn version is 1.3.2.

**Comment by Harryqu123** [comment]
Thanks for your timely response. 

Yes I mean by system memory. In that case, could I please kindly know the system memory of your machine?

I am asking because, when I run the script, I find that it can occupy more than all the 126G + 117G system memory screenshotted below. I guess that it may be strange for the script to require such a large system memory. Sorry for bothering
![image](https://github.com/user-attachments/assets/447a99fa-349e-45be-81f6-d99f0f24f352)

**Comment by danpeng2** [comment]
![00](https://github.com/user-attachments/assets/8f5e7e91-6eff-4209-8a68-0189bd3cc49d)

We tested the scan24 sequence, and the maximum memory usage was 5GB.

**Comment by Harryqu123** [comment]
Many thanks! 

Yet the thing becomes a bit tricky here as we share the same python and sklearn version lol.

Anyway thanks for your timely information and have a good day ahead :)

I will try to figure some way to further debug my code.

**Comment by Saixiaoma** [comment]
Do you resolved this problem?

**Comment by Harryqu123** [comment]
Hi there. Yes I have resolved the problem. The only thing to do is to strictly follow this repo's preprocecssing, instead of co-referring some of the rest repo's ones. I believe that I originally accidentally jump over some of the preprocessing steps listed in the Read Me and this causes the error
