### ISSUE TITLE
Out of memory when evaluating DTU mesh

### ISSUE THREAD

**Issue by ingra14m** [zju3dv/PGSR#15]
Hi, thanks for the great work!

I found that the reconstructed mesh (around 500MB) in DTU dataset has too many faces, which will lead to oom errors upon executing [radius_neighbors](https://github.com/zju3dv/PGSR/blob/5ac466853b115ab55adf93ed41850782d2f300bd/scripts/dtu_eval.py#L123).

My computer has 32GB RAM and RTX 3090 with 24GB VRAM. I have no idea if this problem stems from the memory or something else I have ignored. Tks so much for your help!

> downsample pcd:  33%|█████████████████████████                                                  | 3/9 [05:31<10:41, 106.98s/it]
[1]    3137183 killed     python scripts/dtu_eval.py --data  --scan 69 --mode mesh --dataset_dir

**Comment by danpeng2** [comment]
Hello, thank you for your interest in our work. 

The reconstructed Mesh size from the DTU scan69 sequence is approximately 60M. May I ask if your DTU dataset includes mask? Has [this line of code](https://github.com/zju3dv/PGSR/blob/5ac466853b115ab55adf93ed41850782d2f300bd/scripts/render_dtu.py#L222C1-L223C1) been executed? Could you show the reconstructed Mesh image?

**Comment by ingra14m** [comment]
Hi, thanks for the prompt reply.

I have identified the problem, which stemmed from an incorrect method of generating the mesh used for evaluation.

Initially, I used python render.py -m path, which generated the mesh without a mask.

When I used scripts/render_dtu.py -m path, the evaluation code ran successfully.
