### ISSUE TITLE
 How can I obtain textures mesh~

### ISSUE THREAD

**Issue by kimwao** [zju3dv/PGSR#16]
Hello! Thank you very much for your work and the open-source code. I have performed Training and Evaluation using the DTU dataset but didn't see the Textures Mesh. How can I obtain it?

**Comment by kimwao** [comment]
`o3d.io.write_triangle_mesh(os.path.join(path, "tsdf_fusion.ply"), mesh, 
                                       write_triangle_uvs=True, write_vertex_colors=True, write_vertex_normals=True)`
The mesh obtained through this line of code has no texture and color, even though write_vertex_colors=True

**Comment by danpeng2** [comment]
Hello, thank you for your interest in our work. We have updated the mesh extraction code. Please pull the latest code and try it again.

**Comment by kimwao** [comment]
Thank you for your timely reply. The textured mesh has been obtainable~
