### ISSUE TITLE
Multi-camera data

### ISSUE THREAD

**Issue by li1u** [zju3dv/PGSR#17]
Hello, I am amazed by the results of your paper, it is really beautiful. But now there is a problem, when I process multi-camera data (renderme360 dataset), the effect becomes strange.
![image](https://github.com/user-attachments/assets/160f8c96-3dff-4cb5-80fe-7e3d4bc65265)

I have adjusted the code for the data reading part (json):
![image](https://github.com/user-attachments/assets/6e2d6fba-293c-4e5b-8b9a-6670917fb7c6)
I don't know why, but if you read cx and cy directly, you will get an error, so use prcppoint to calculate.
 projection matrix:
 
![image](https://github.com/user-attachments/assets/4034a5fc-7612-48c1-9e69-a9f5ebe68b76)
![image](https://github.com/user-attachments/assets/16a445a4-7437-412e-88a8-780e239c3257)

The projection matrix in sample_cam has also been modified accordingly.

![30000_00000014](https://github.com/user-attachments/assets/985d27f7-227e-4348-bb0e-8e2c602ad608)
(The last image)

**Comment by danpeng2** [comment]
Hello, thank you for recognizing our work. 

We have not yet conducted a complete test on the configuration where the camera intrinsic parameters are not at the center of the image. I suggest cropping the original image so that the camera intrinsic parameters are at the center of the image.

**Comment by li1u** [comment]
![image](https://github.com/user-attachments/assets/b3f5b75f-8561-4bc8-b652-14bbdea62cc7)
It should just be that the size is set too large, but I feel there are still some problems that need to be solved.

**Comment by danpeng2** [comment]
The surface noise is quite significant. If there are no special reflections or lighting changes in the image, the surface should be relatively smooth, indicating there are indeed some issues that need to be addressed. Here are my recommended troubleshooting directions:

1. Check the output multi_view.json to confirm if appropriate frames have been selected.
2. Ensure the camera poses are accurate enough. It is best to use COLMAP for fine-tuning.
3. Avoid using unverified features like getProjectionMatrixCenterShift.
