### ISSUE TITLE
about multi-view consistency

### ISSUE THREAD

**Issue by cv-lab-x** [zju3dv/PGSR#2]
hi, thanks for your work, did you test multi-view photometric consistency on rgb color or decoupled rgb color? 
and how many neighboring frames did you test ? Looking forward to your reply, thanks. @danpeng2

**Comment by danpeng2** [comment]
Photometric loss has not been tested on RGB; however, based on previous experience, RGB does not provide any gain. We use only one neighboring frame per iteration. For detailed usage, please refer to our code.
