### ISSUE TITLE
How to run the code on Replica Dataset like your paper

### ISSUE THREAD

**Issue by laliwang** [zju3dv/PGSR#21]
First thanks for your excellent work and sharing! From your paper, I have noticed that you evaluate PGSR on Replica dataset like office. However, when I try to reproduce it on replica dataset like room0, the colmap process failed. Could you please give me some suggestions for evaluating on replica dataset or other scene-level dataset like ScanNet? Thanks a lot!

**Comment by danpeng2** [comment]
Hello, thank you for your interest in our work. 

We download the replica data from this [address](https://www.dropbox.com/scl/fo/puh6djua6ewgs0afsswmz/AGudMbll0n0v_iADmqrrRds?rlkey=ep5495umv628y2sk8hvnh8msc&e=2&dl=0) and then use our script for preprocessing. You can give it a try.

**Comment by xi-zc** [comment]
> Hello, thank you for your interest in our work.
> 
> We download the replica data from this [address](https://www.dropbox.com/scl/fo/puh6djua6ewgs0afsswmz/AGudMbll0n0v_iADmqrrRds?rlkey=ep5495umv628y2sk8hvnh8msc&e=2&dl=0) and then use our script for preprocessing. You can give it a try.

Thank you very much for your prompt response and for sharing the link to the Replica dataset.
You mentioned that you use your own script for preprocessing the Replica(and maybe scannet) data. Would it be possible for you to share this preprocessing script as well? Having access to it would be immensely helpful for me to ensure consistency and accurately replicate your data preparation steps.
Thank you again for your help！
