### ISSUE TITLE
how to disambuiguity normals of gaussian splatting

### ISSUE THREAD

**Issue by wangmiaowei** [zju3dv/PGSR#22]
Thanks for your great job. I have a question, how to get the normals for each gaussian, I know you use the shortest axis, but then make all direction should be greater than 90 degree from camera shooting direction. but how to disambuguity that globally.

**Comment by danpeng2** [comment]
Hello, thank you for your interest in our work. 
We have not established a globally unique normal vector; instead, we determine the current normal of the Gaussian based on the camera view. If you want to have a globally unique normal vector, you might need to define and record the global Gaussian normal during the initialization phase.
