### ISSUE TITLE
A question about AssertionError: While the loader support other types, the rest of the code assumes PINHOLE

### ISSUE THREAD

**Issue by landax-223** [zju3dv/PGSR#24]
Thank you for your excellent work 
My question is about read_intrinsics_text. I check my camera.txt, the camera model is SIMPLE_RADIAL.
I know the original 3D GS also request SIMPLE_PINHOLE. But I can run work when I use data like spaerse/camera.db and image.db point3D.db in the 3D GS
Can you tell me how to run PGSR correctly?

**Comment by danpeng2** [comment]
Hello, thank you for your interest in our work. 
I suggest you use our preprocessing script to generate the corresponding SIMPLE_PINHOLE camera model.

**Comment by landax-223** [comment]
ok,I will try  it. Thank you for enthusiastic reply
