### ISSUE TITLE
The effect of high-resolution images on results

### ISSUE THREAD

**Issue by fy99925** [zju3dv/PGSR#30]
I used A100 on the server to train the original resolution image (almost 5600*3600), with all parameters unchanged and 30,000 iterations. The result is blurrier than the image training that is automatically cropped to 1.6k. It is strange. I think higher resolution images may lead to better results.

I wonder about this, what is the effect of high resolution images on guassian splatting? How can I use high resolution images better in gs?

**Comment by 3406212002** [comment]
Hi,I am also interestd in this issue,have  you solved this problem?  and I wander How much the accuracy can be improved if high resolution images was used?
