### ISSUE TITLE
Depth map calculation problem

### ISSUE THREAD

**Issue by 18128381510** [zju3dv/PGSR#37]
Thank you for your excellent work, but I currently have a few confusions:
1. I noticed that when calculating the depth map in the paper, the rays distance is obtained instead of the z-value of rays. Is this a problem?
2. Does not normalizing K-1*p affect the accuracy of cos value, is there a precision issue with this?

**Comment by danpeng2** [comment]
Thank you for your interest in our work.
1. We obtain the plane-to-camera distance, the normal vector, and the corresponding ray, which are then transformed into the intersection point of the ray and the plane, i.e., the depth.
2. No normalization is required, as the formula provides an exact calculation without approximation.

**Comment by 18128381510** [comment]
You are right, thanks!

**Comment by booker-max** [comment]
> Thank you for your interest in our work.
> 
> 1. We obtain the plane-to-camera distance, the normal vector, and the corresponding ray, which are then transformed into the intersection point of the ray and the plane, i.e., the depth.
> 2. No normalization is required, as the formula provides an exact calculation without approximation.

在你的代码中，local_distance是这么计算出来的，local_distance = (local_normal * pts_in_cam).sum(-1).abs()，但是我好奇的是 这个是计算x1+x2+x3，但是distance不是应该用sqrt(x1**2+x2**2+x3**2)么

**Comment by venite-xjc** [comment]
> > Thank you for your interest in our work.
> > 
> > 1. We obtain the plane-to-camera distance, the normal vector, and the corresponding ray, which are then transformed into the intersection point of the ray and the plane, i.e., the depth.
> > 2. No normalization is required, as the formula provides an exact calculation without approximation.
> 
> 在你的代码中，local_distance是这么计算出来的，local_distance = (local_normal * pts_in_cam).sum(-1).abs()，但是我好奇的是 这个是计算x1+x2+x3，但是distance不是应该用sqrt(x1**2+x2**2+x3**2)么

Hi，I'm also confused about this, do you have any idea?
