### ISSUE TITLE
Using gt images instead of rendered images for TSDF

### ISSUE THREAD

**Issue by kimwao** [zju3dv/PGSR#42]
Hello, I noticed that when using ground truth images instead of rendered images for TSDF to get rgbd, the resulting mesh shows no significant difference. Additionally, the process is faster since there's no need to save the images. Do you think this approach might be problematic?

**Comment by danpeng2** [comment]
If the primary concern is surface reconstruction quality rather than rendering itself, I believe this approach is feasible.
