### ISSUE TITLE
In the paper, there is an issue with the Image Edge-Aware Single-View Loss.

### ISSUE THREAD

**Issue by kimwao** [zju3dv/PGSR#43]
![55](https://github.com/user-attachments/assets/a0638f16-c90e-4319-9452-777756cbe1c6)
In the Image Edge-Aware Single-View Loss, should the "gradient(I)" be modified to 1−𝐼𝑔

**Comment by danpeng2** [comment]
Yes, you're right! Thank you for your feedback.
