### ISSUE TITLE
How to fit the PGSR's output to the viewer of the vanilla GS?

### ISSUE THREAD

**Issue by Harr7y** [zju3dv/PGSR#44]
Hi, thanks a lot for the brilliant work. I want to know how to modify the codes to make the output GS of the PGSR to be suitable for viewer of Vanilla GS for the **Ellipsoids** Render. It's compatible to the Splats Render.

**Comment by danpeng2** [comment]
Hello, our GS expression format is the same as Vanilla GS's and is suitable for the viewer of Vanilla GS.
