### ISSUE TITLE
string is not a file: output_dtu_1/dtu_scan24/test1/mesh/tsdf_fusion_post.ply

### ISSUE THREAD

**Issue by 1030366507** [zju3dv/PGSR#46]
When I run the script that trains the dtu, the ply file is not generated, making it impossible to evaluate，please help me！thank you！

**Comment by danpeng2** [comment]
Hello, are there any error messages? During training, you can remove the --quiet parameter to allow error information to be printed.

**Comment by 1030366507** [comment]
It's because of open3d. The gblic version is wrong，You've had that problem before？
