### ISSUE TITLE
The code in densify_and_split

### ISSUE THREAD

**Issue by kimwao** [zju3dv/PGSR#50]
![2024-10-16_231604](https://github.com/user-attachments/assets/dc5d36c6-1acf-4b0f-ba4f-3f27496a9162)
padded_grads_abs[selected_pts_mask] = 0 should be changed to padded_grads_abs[~selected_pts_mask] = 0.

**Comment by 1030366507** [comment]
这个有啥影响吗？

**Comment by GuangyuWang99** [comment]
I don't think this should be changed. `padded_grads_abs` is used to compute `selected_pts_mask_abs`, which is another set of points threshold by 3D scaling and 2D scaling to **complement** `selected_pts_mask` (See `torch.logical_or` in L445). And the logic is that there should be no intersections between `selected_pts_mask_abs` and `selected_pts_mask_abs`.

**Comment by kimwao** [comment]
> I don't think this should be changed. `padded_grads_abs` is used to compute `selected_pts_mask_abs`, which is another set of points threshold by 3D scaling and 2D scaling to **complement** `selected_pts_mask` (See `torch.logical_or` in L445). And the logic is that there should be no intersections between `selected_pts_mask_abs` and `selected_pts_mask_abs`.

Yes, you're right! Thank you
