### ISSUE TITLE
[Code] Missing dependency in the diff_plane_rasterization

### ISSUE THREAD

**Issue by NK-CS-ZZL** [zju3dv/PGSR#6]
In the folder `diff_plane_rasterization/third_party`, the dependency `glm` seems missing, causing compiling errors.

**Comment by NK-CS-ZZL** [comment]
This can be fix by copying the folder for 3DGS repo. The authors could fix the issue when convenience.

**Comment by danpeng2** [comment]
Thank you very much for your feedback. We have already fixed the related issues.

**Comment by NK-CS-ZZL** [comment]
BTW, the image path in `convert_dtu` is not right. You can refer to the PR #7

**Comment by danpeng2** [comment]
Thank you very much. I didn't notice this PR earlier, but it has now been manually fixed.
