### ISSUE TITLE
After training, mesh reconstruction is killed. Is it because there are too many Gaussians in the scene?

### ISSUE THREAD

**Issue by Gatswei** [zju3dv/PGSR#62]
Excellent work! But I encounter a problem, when I use my custom data. After training, mesh reconstruction is killed. Is it because there are too many Gaussians in the scene? How to solve this problem？

**Comment by danpeng2** [comment]
Hello, is there an error message? Since the algorithm has a maximum Gaussian point limit set, it is unlikely that the mesh extraction issue is caused by having too many Gaussian points.

**Comment by Gatswei** [comment]
There's no any error occur, just be killed. When I adjust voxel_size higher, my problem can be solved.
