### ISSUE TITLE
Test on TnT dataset

### ISSUE THREAD

**Issue by Saixiaoma** [zju3dv/PGSR#64]
I used the relevant parameters in run_tnt.py for training, and the RGB rendering results of the training results were very poor. When testing on the TnT dataset, is it necessary to use a semantic segmentation mask to remove background areas such as the sky?

**Comment by danpeng2** [comment]
Hello, semantic segmentation is not required. Is the TnT dataset processed according to the README?

**Comment by Saixiaoma** [comment]
yes, I use convert_tnt.py to process tnt data.

**Comment by Saixiaoma** [comment]
Thank you for your reply. I found that there may be some problems with the code I downloaded before.
