### ISSUE TITLE
关于H矩阵的计算

### ISSUE THREAD

**Issue by wangyupengCC** [zju3dv/PGSR#66]
作者你好，首先感谢你们能开源这么优秀的项目，在阅读论文过程中有如下疑问
（1）请问论文中的公式8的H矩阵是如何推导来的
（2）在multi-view  Photometric 中采用11个像素作为patch，是不是将这11个块认为在同一个平面了呢（做了这样的强假设）
期待你的回复

**Comment by danpeng2** [comment]
你好。
（1）可以参考书籍《An Invitation to 3-D Vision》中108页关于Homography的公式
（2）是的，认为整个patch是一个平面

**Comment by wangyupengCC** [comment]
收到，感谢回复^_^
