### ISSUE TITLE
What is the difference between render_pkg['rendered_distance'] and render_pkg['plane_depth']?

### ISSUE THREAD

**Issue by mappro6** [zju3dv/PGSR#67]
Is render_pkg['rendered_distance'] the depth we finally render? But the code uses render_pkg['plane_depth'] to get the depth_normal, which confuses me. Could you provide some guidance?

**Comment by danpeng2** [comment]
Hello. The relationship between **distance** and **depth** can be referred to in Equation 4 of the paper. **rendered_distance** corresponds to **plane distance** in Figure 6, while **plane_depth** corresponds to **depth**. **rendered_distance** represents the distance from the plane to the camera center, and **plane_depth** represents the depth map.

**Comment by mappro6** [comment]
@danpeng2 Thank you!
