### ISSUE TITLE
Segmentation fault (core dumped) when training

### ISSUE THREAD

**Issue by guishe666** [zju3dv/PGSR#8]
Hi, Thanks for the awesome work! I met a problem when training the model. 

It will report "Segmentation fault (core dumped)"  when calculating `lncc` in file `loss_utils.py`. It occurs when using the function **F.conv2d**. 

I found it probably because the version of PyTorch. Related: [Segmentation Fault in PyTorch 2.2 with F.conv3d function](https://github.com/pytorch/pytorch/issues/120406)
I solved by reducing the version of PyTorch to `2.0.0`.

my environment info:
OS: Ubuntu 22.04
Device: Nvidia RTX 4090
Cuda version: 11.8

**Comment by danpeng2** [comment]
Thank you for your feedback. We have used the PyTorch 2.3.1 version and have not encountered this error.

**Comment by David-Zhao-1997** [comment]
Had the same problem with Pytorch 2.2.1+cu118, upgrading PyTorch 2.4.0 solved the problem.
