### ISSUE TITLE
train speed

### ISSUE THREAD

**Issue by chenqi13814529300** [zju3dv/PGSR#9]
I feel your work is great, I will test it next. May I ask if the training speed can be improved? Can we refer to the optimization method of 2D Gaussian for rasterization?

**Comment by ywcmaike** [comment]
Theoretically, it should be possible to replace the planar representation of PGSR with 2DGS, but we have not tried it. We have applied PGSR to different settings and will release a large reconstruction framework next month. You are encouraged to update the results for this issue. The key to PGSR's superiority over existing GS-based surface reconstruction lies in unbiased depth estimation, single-view constraints, multi-view constraints, and camera compensation. If you add the key technologies of PGSR to 2DGS, you may get a significant performance improvement.
